[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.23"
gas_reports = ["Counter"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
